### ISSUE TITLE
Bug: not possible to build mapping in case the target property is involved in a function call

### ISSUE THREAD

**Issue by sszuev** [avicomp/ont-map#20]
The following testcase leads to exception:

            OntGraphModel src = OntModelFactory.createModel().setNsPrefixes(OntModelFactory.STANDARD);
            src.setID("http://src");
            OntClass c1 = src.createOntEntity(OntClass.class, "C1");
            c1.createIndividual("I1");;

            OntGraphModel dst = OntModelFactory.createModel().setNsPrefixes(OntModelFactory.STANDARD);
            dst.setID("http://dst");
            OntClass c2 = dst.createOntEntity(OntClass.class, "C2");
            OntNAP p2 = dst.createOntEntity(OntNAP.class, "P2");
            p2.addDomain(c2);
            p2.addRange(XSD.xstring.inModel(dst).as(OntDT.class));
            OntNAP p1 = dst.createOntEntity(OntNAP.class, "P1");
            p1.addDomain(c2);

            MapManager man = Managers.createMapManager();
            MapFunction.Call uuid = man.getFunction(AVC.UUID).create().build();
            MapFunction eq = man.getFunction(SPINMAP.equals);
            MapModel map = man.createMapModel();
            map.createContext(c1, c2, uuid)
                    .addPropertyBridge(eq.create()
                            .add(SP.arg1.getURI(), p1.getURI()).build(), p2);

The exception:

```
Exception in thread "main" ru.avicomp.map.MapJenaException$Unsupported: TODO: expressions with arguments from right side are not supported right now.
	at ru.avicomp.map.spin.ContextHelper.addExpression(ContextHelper.java:271)
	at ru.avicomp.map.spin.ContextHelper.populate(ContextHelper.java:95)
	at ru.avicomp.map.spin.MapContextImpl.addPropertyBridge(MapContextImpl.java:170)
	at ru.avicomp.map.spin.MapContextImpl.addPropertyBridge(MapContextImpl.java:62)
	at ru.avicomp.map.MapContext.addPropertyBridge(MapContext.java:213)
	at ru.avicomp.map.tmp.Tmp_ContextHelperBug$B.main(Tmp_ContextHelperBug.java:105)
```

**Comment by sszuev** [comment]
fixed
