### ISSUE TITLE
Bug: ConcurrentModificationException while inference if source and target match

### ISSUE THREAD

**Issue by sszuev** [avicomp/ont-map#21]
The following testcase leads to exception:

        OntGraphModel m = OntModelFactory.createModel().setNsPrefixes(OntModelFactory.STANDARD);
        m.setID("http://src");
        OntClass c1 = m.createOntEntity(OntClass.class, "C1");
        c1.createIndividual("I1");
        OntClass c2 = m.createOntEntity(OntClass.class, "C2");

        MapManager man = Managers.createMapManager();
        MapFunction.Call uuid = man.getFunction(AVC.UUID).create().build();
        MapModel map = man.createMapModel();
        map.createContext(c1, c2, uuid);
        man.getInferenceEngine(map).run(m, m);

The exception:
```

Exception in thread "main" java.util.ConcurrentModificationException
	at org.apache.jena.mem.ArrayBunch$2.hasNext(ArrayBunch.java:118)
	at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
	at org.apache.jena.util.iterator.FilterIterator.hasNext(FilterIterator.java:55)
	at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
	at org.apache.jena.util.iterator.WrappedIterator.hasNext(WrappedIterator.java:90)
	at org.apache.jena.util.iterator.Map1Iterator.hasNext(Map1Iterator.java:49)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at ru.avicomp.map.spin.infer.InferenceEngineImpl.run(InferenceEngineImpl.java:176)
	at ru.avicomp.map.spin.infer.InferenceEngineImpl.run(InferenceEngineImpl.java:123)
	at ru.avicomp.map.MapManager$InferenceEngine.run(MapManager.java:216)
	at ru.avicomp.map.tmp.Tmp_ConcurrModificationExceptionBug.main(Tmp_ConcurrModificationExceptionBug.java:53)
```

**Comment by sszuev** [comment]
Fix is provided. 
Although, now there is no better solution than put data to memory for such a case. 
Do not mix source and target in case of big data!

**Comment by sszuev** [comment]
It seems this issue is not fully fixed.
